aws:
  dora_dir: ${oc.env:HOME}/audiocraft-output/experiments/audiocraft/outputs
  reference_dir: ${oc.env:HOME}/audiocraft-output/shared/audiocraft/reference
  dataset_mappers:
    "^/checkpoint/[a-z]+": "${oc.env:HOME}/audiocraft-output"
default:
  dora_dir: ${oc.env:HOME}/audiocraft-output/experiments/audiocraft/outputs
  reference_dir: ${oc.env:HOME}/audiocraft-output/shared/audiocraft/reference
  partitions:
    global: debug
    team: debug